services:
  postgres:
    build:
      context: ./
      dockerfile: postgres/Dockerfile
    container_name: postgres_db
    ports:
      - 5432:5432
    env_file:
      - ../.env
  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_POSTGRES: ${POSTGRES_HOST}
      REDMINE_DB_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  postgres_data:
    driver: local
